import type { NextPage } from 'next';
import Head from 'next/head';
import { sample } from 'underscore';
import { ClipLoader } from 'react-spinners';
import { useState } from 'react';

const Home: NextPage = ({ stories }: any) => {
  const [regenerating, setRegenerating] = useState(false);

  const onRegenerate = async () => {
    setRegenerating(true);
    await fetch(`${window.location.origin}/api/revalidate`)
      .then((res) => res.json())
      .then((_data) => setTimeout(() => window.location.reload(), 2000));
  };

  return (
    <div>
      <Head>
        <title>HN Static Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col">
        <div className="flex justify-end">
          <ClipLoader loading={regenerating} className="mt-6" />
          <button className="btn btn-primary m-5 mr-20 z-10" type="button" onClick={onRegenerate}>Regenerate Stories</button>
        </div>
        <div className="flex justify-center mb-5">
          <p className="text-center w-[800px]">
            This site is a demo for Next JS&apos;s on-demand static regeneration feature. It will randomly pull 200 of
            the current top 500 HackerNews stories for display. Clicking the &apos;Regenerate Stories&apos; button will make a request to activate
            Next&apos;s on-demand static regeneration for this site, picking a new random 200 HN stories.
          </p>
        </div>
        <div className="flex justify-center">
          <div className="flex flex-col items-start ml-3 mr-3 mb-5">
            {stories.map((story: any) => (
              <div className="mt-3 mb-3" key={story.id}>
                {story.url
                  ? (
                    <a className="link link-primary" href={story.url}>
                      {story.title}
                    </a>
                  )
                  : <span>{story.title}</span>}
                {' '}
                (
                {story.time}
                ) -
                {' '}
                <a className="link link-primary" href={story.comments}>Comments Link</a>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
};

const STORY_NUM = 100;

export async function getStaticProps() {
  const res = await fetch('https://hacker-news.firebaseio.com/v0/topstories.json');
  const storyIds = await res.json();
  const randStoryIds = sample(storyIds, STORY_NUM);

  const stories: any[] = [];
  // eslint-disable-next-line no-restricted-syntax
  for await (const id of randStoryIds) {
    const storyRes = await fetch(`https://hacker-news.firebaseio.com/v0/item/${id}.json`);
    const storyObj = await storyRes.json();
    const date = new Date(0); // The 0 there is the key, which sets the date to the epoch
    date.setUTCSeconds(storyObj.time);
    const time = date.toLocaleDateString('en-us', {
      weekday: 'long', year: 'numeric', month: 'short', day: 'numeric', hour: 'numeric', minute: 'numeric',
    });
    stories.push({
      id,
      title: storyObj.title,
      url: storyObj?.url ?? null,
      comments: `https://news.ycombinator.com/item?id=${id}`,
      time,
    });
  }

  return {
    props: { stories },
  };
}

export default Home;
